# -*- coding: utf-8 -*-
"""llamaCorrupcion_master.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTUS0IL9e_BRQ59bRTyGhCrtZvRXiIbj
"""

import re
import csv
import gc
import os
from collections import defaultdict
import torch
from google import genai
import formulario

# =========================================================
# CONFIG
# =========================================================

PROCESSED_LOG = "processed_gemini.txt"
FAILED_LOG = "failed_gemini.txt"
CSV_PATH = "responses_gemini.csv"
DIRECTORIO = "./all_pages_clean/"
N_REPS = 3

CSV_COLS = [
    'pagina', 'tipo_entidad', 'origen_entidad', 'proposito',
    'informacion_presentada', 'vision', 'consecuencias', 'que_muestra',
    'intencion', 'localizacion_problema', 'involucrados', 'formalidad',
    'nivel_educacion', 'tono', 'emociones'
]
QUESTIONS = CSV_COLS[1:]

FORMULAIRE = [
    formulario.q1_tipo_entidad,
    formulario.q2_origen_entidad,
    formulario.q3_proposito,
    formulario.q4_informacion_presentada,
    formulario.q5_vision,
    formulario.q6_consecuencias,
    formulario.q7_que_muestra,
    formulario.q8_intencion,
    formulario.q9_localidad_problema,
    formulario.q10_involucrados,
    formulario.q11_formalidad,
    formulario.q12_nivel_educacion,
    formulario.q13_tono,
    formulario.q14_emociones
]

# =========================================================
# UTILS
# =========================================================

def collect_garbage(*objs):
    for obj in objs:
        try:
            del obj
        except Exception:
            pass
    gc.collect()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def cleanup_gpu():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def append_log(log_path: str, file_id: str, question: str | None = None, response_text: str | None = None):
    """
    Si se pasa question y response_text:
        file_id \\t question \\t response_text
    Si no:
        file_id
    """
    with open(log_path, "a", encoding="utf-8") as f:
        if question is None:
            f.write(f"{file_id}\n")
        else:
            safe_text = "" if response_text is None else response_text.replace("\n", " ").strip()
            f.write(f"{file_id}\t{question}\t{safe_text}\n")
        f.flush()
        os.fsync(f.fileno())

def load_failed_set(log_path: str) -> set[str]:
    failed = set()
    if not os.path.exists(log_path):
        return failed

    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            file_id = line.split("\t", 1)[0].strip()
            if file_id:
                failed.add(file_id)
    return failed

def load_progress(log_path: str):
    """
    Lee processed_gemini.txt con formato:
        file_id \\t question \\t response_text

    Regresa:
        answers[file_id][question] = [resp1, resp2, resp3, ...]
    """
    answers = defaultdict(lambda: defaultdict(list))

    if not os.path.exists(log_path):
        return answers

    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue

            parts = line.split("\t", 2)
            if len(parts) < 3:
                continue

            file_id, question, response_text = parts[0].strip(), parts[1].strip(), parts[2].strip()

            if file_id and question in QUESTIONS:
                answers[file_id][question].append(response_text)

    return answers

def file_is_complete(file_id: str, answers, n_reps: int = N_REPS) -> bool:
    return all(len(answers[file_id].get(q, [])) >= n_reps for q in QUESTIONS)

def get_missing_questions(file_id: str, answers, n_reps: int = N_REPS):
    """
    Regresa dict:
        missing[q] = cuántas ejecuciones faltan de esa pregunta
    """
    missing = {}
    for q in QUESTIONS:
        done = len(answers[file_id].get(q, []))
        if done < n_reps:
            missing[q] = n_reps - done
    return missing

def extract_incisos(response_text: str) -> str:
    """
    Extrae incisos tipo a), b), c), ...
    """
    if not response_text:
        return ""

    m = re.findall(r'(^|[\s]|\*|")([a-i](?:\)|,|\.))', response_text, flags=re.IGNORECASE)
    return ' '.join(t[1] for t in m)

def rebuild_csv_from_log(processed_log: str, csv_path: str):
    """
    Reconstruye responses_gemini.csv desde cero a partir del log.
    Usa la ocurrencia n de cada pregunta como la repetición n.
    Solo escribe filas completas.
    """
    answers = load_progress(processed_log)

    file_ids = sorted(answers.keys())

    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter=';')
        writer.writerow(CSV_COLS)

        for file_id in file_ids:
            # número máximo de repeticiones completas que se pueden armar
            max_complete = min(len(answers[file_id].get(q, [])) for q in QUESTIONS)

            for rep_idx in range(max_complete):
                row = [file_id]
                complete = True

                for q in QUESTIONS:
                    try:
                        response_text = answers[file_id][q][rep_idx]
                    except IndexError:
                        complete = False
                        break

                    incisos = extract_incisos(response_text)
                    row.append(incisos)

                if complete:
                    writer.writerow(row)

        f.flush()
        os.fsync(f.fileno())

# =========================================================
# CLIENT
# =========================================================

print("CWD:", os.getcwd())

os.environ["GEMINI_API_KEY"] = "AIzaSyCBCzebcGkBLCXUsNV1ekb0djQDUbdqV8c"
client = genai.Client()
#model = "gemini-3.1-pro-preview"
model = "gemini-2.5-flash"


# =========================================================
# MAIN
# =========================================================

archivos = sorted(os.listdir(DIRECTORIO))
if ".ipynb_checkpoints" in archivos:
    archivos.remove(".ipynb_checkpoints")

answers = load_progress(PROCESSED_LOG)
failed = load_failed_set(FAILED_LOG)

for file in archivos:
    file_id = file[:4]

    if file_id in failed:
        print(f"Saltando {file_id}: está en FAILED_LOG")
        continue

    if file_is_complete(file_id, answers):
        print(f"Saltando {file_id}: ya completo")
        continue

    print(f"\nProcesando {file}")
    print("Faltan:", get_missing_questions(file_id, answers))

    try:
        with open(os.path.join(DIRECTORIO, file), "r", encoding="utf-8") as fh:
            input_text = fh.read()

        for pregunta_func, q_name in zip(FORMULAIRE, QUESTIONS):
            done = len(answers[file_id].get(q_name, []))
            faltan = N_REPS - done

            if faltan <= 0:
                continue

            for _ in range(faltan):
                print(f"\t{q_name} ({done + 1}/{N_REPS})")

                message = pregunta_func(input_text)

                response = client.models.generate_content(
                    model=model,
                    contents=message,
                )

                response_text = response.text if response.text is not None else ""

                append_log(PROCESSED_LOG, file_id, q_name, response_text)
                answers[file_id][q_name].append(response_text)

                done += 1
                collect_garbage(message, response)

    except torch.OutOfMemoryError:
        if file_id not in failed:
            failed.add(file_id)
            append_log(FAILED_LOG, file_id, "OOM", "OOM")
        print("OOM:", file_id)
        cleanup_gpu()

    except Exception as e:
        if file_id not in failed:
            failed.add(file_id)
            append_log(FAILED_LOG, file_id, "ERROR", repr(e))
        print("ERR:", file_id, repr(e))
        cleanup_gpu()

# reconstruir CSV completo al final
rebuild_csv_from_log(PROCESSED_LOG, CSV_PATH)
print(f"\nCSV reconstruido en: {CSV_PATH}")