# -*- coding: utf-8 -*-
"""llamaCorrupcion_master.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTUS0IL9e_BRQ59bRTyGhCrtZvRXiIbj
"""

import re
import formulario_gemma as formulario
import csv
import os
import time
from collections import deque
from collections import defaultdict

# =========================================================
# CONFIG
# =========================================================

PROCESSED_LOG = "processed_gemini.txt"
FAILED_LOG = "failed_gemini.txt"
CSV_PATH = "responses_gemini.csv"
DIRECTORIO = "./all_pages_clean/"
N_REPS = 3

CSV_COLS = [
    'pagina', 'tipo_entidad', 'origen_entidad', 'proposito',
    'informacion_presentada', 'vision', 'consecuencias', 'que_muestra',
    'intencion', 'localizacion_problema', 'involucrados', 'formalidad',
    'nivel_educacion', 'tono', 'emociones'
]
QUESTIONS = CSV_COLS[1:]

FORMULAIRE = [
    formulario.q1_tipo_entidad,
    formulario.q2_origen_entidad,
    formulario.q3_proposito,
    formulario.q4_informacion_presentada,
    formulario.q5_vision,
    formulario.q6_consecuencias,
    formulario.q7_que_muestra,
    formulario.q8_intencion,
    formulario.q9_localidad_problema,
    formulario.q10_involucrados,
    formulario.q11_formalidad,
    formulario.q12_nivel_educacion,
    formulario.q13_tono,
    formulario.q14_emociones
]

#!pip install trl
#!pip uninstall bitsandbytes
#!pip install bitsandbytes>=0.41.1

'''
import torch

if torch.cuda.get_device_capability()[0] >= 8:
    attn_implementation = "flash_attention_2"
    torch_dtype = torch.bfloat16
else:
    attn_implementation = "sdpa"#"eager"
    torch_dtype = torch.float16

import gc
import os
import pickle
from datasets import load_dataset
from peft import LoraConfig, PeftModel, prepare_model_for_kbit_training

from transformers import (
    AutoModelForCausalLM,
    AutoProcessor,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    pipeline,
)
from trl import ORPOConfig, ORPOTrainer

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb=128"

#if memory staurates, garbage collector can be programmed periodically
def collect_garbage(input_message, output):
  del input_message
  del output
  gc.collect()
  gc.collect()
  torch.cuda.empty_cache()

def cleanup_gpu():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
'''

# =========================================================
# UTILS
# =========================================================

def append_log(log_path: str, file_id: str, question: str | None = None, response_text: str | None = None):
    """
    Si se pasa question y response_text:
        file_id \\t question \\t response_text
    Si no:
        file_id
    """
    with open(log_path, "a", encoding="utf-8") as f:
        if question is None:
            f.write(f"{file_id}\n")
        else:
            safe_text = "" if response_text is None else response_text.replace("\n", " ").strip()
            f.write(f"{file_id}\t{question}\t{safe_text}\n")
        f.flush()
        os.fsync(f.fileno())

def load_failed_set(log_path: str) -> set[str]:
    failed = set()
    if not os.path.exists(log_path):
        return failed

    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            file_id = line.split("\t", 1)[0].strip()
            if file_id:
                failed.add(file_id)
    return failed

def load_progress(log_path: str):
    """
    Lee processed_gemini.txt con formato:
        file_id \\t question \\t response_text

    Regresa:
        answers[file_id][question] = [resp1, resp2, resp3, ...]
    """
    answers = defaultdict(lambda: defaultdict(list))

    if not os.path.exists(log_path):
        return answers

    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue

            parts = line.split("\t", 2)
            if len(parts) < 3:
                continue

            file_id, question, response_text = parts[0].strip(), parts[1].strip(), parts[2].strip()

            if file_id and question in QUESTIONS:
                answers[file_id][question].append(response_text)

    return answers

def file_is_complete(file_id: str, answers, n_reps: int = N_REPS) -> bool:
    return all(len(answers[file_id].get(q, [])) >= n_reps for q in QUESTIONS)

def get_missing_questions(file_id: str, answers, n_reps: int = N_REPS):
    """
    Regresa dict:
        missing[q] = cuántas ejecuciones faltan de esa pregunta
    """
    missing = {}
    for q in QUESTIONS:
        done = len(answers[file_id].get(q, []))
        if done < n_reps:
            missing[q] = n_reps - done
    return missing

def extract_incisos(response_text: str) -> str:
    """
    Extrae incisos tipo a), b), c), ...
    """
    if not response_text:
        return ""

    m = re.findall(r'(^|[\s]|\*|")([a-i](?:\)|,|\.))', response_text, flags=re.IGNORECASE)
    return ' '.join(t[1] for t in m)

def rebuild_csv_from_log(processed_log: str, csv_path: str):
    """
    Reconstruye responses_gemini.csv desde cero a partir del log.
    Usa la ocurrencia n de cada pregunta como la repetición n.
    Solo escribe filas completas.
    """
    answers = load_progress(processed_log)

    file_ids = sorted(answers.keys())

    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter=';')
        writer.writerow(CSV_COLS)

        for file_id in file_ids:
            # número máximo de repeticiones completas que se pueden armar
            max_complete = min(len(answers[file_id].get(q, [])) for q in QUESTIONS)

            for rep_idx in range(max_complete):
                row = [file_id]
                complete = True

                for q in QUESTIONS:
                    try:
                        response_text = answers[file_id][q][rep_idx]
                    except IndexError:
                        complete = False
                        break

                    incisos = extract_incisos(response_text)
                    row.append(incisos)

                if complete:
                    writer.writerow(row)

        f.flush()
        os.fsync(f.fileno())

class RateLimiter:
    def __init__(self, max_requests, time_window_seconds):
        """
        max_requests: número máximo de solicitudes por ventana de tiempo
        time_window_seconds: ventana de tiempo en segundos
        """
        self.max_requests = max_requests
        self.time_window = time_window_seconds
        self.request_times = deque()
    
    def wait_if_needed(self):
        """Espera si es necesario para cumplir con el rate limit"""
        current_time = time.time()
        
        # Limpiar solicitudes fuera de la ventana de tiempo
        while self.request_times and current_time - self.request_times[0] > self.time_window:
            self.request_times.popleft()
        
        # Si ya alcanzamos el límite, esperar hasta que haya espacio
        if len(self.request_times) >= self.max_requests:
            sleep_time = self.time_window - (current_time - self.request_times[0])
            if sleep_time > 0:
                print(f"⏰ Rate limit alcanzado. Esperando {sleep_time:.2f} segundos...")
                time.sleep(sleep_time + 0.1)  # +0.1 para margen de seguridad
                # Recursión para verificar nuevamente
                self.wait_if_needed()
    
    def record_request(self):
        """Registra una solicitud realizada"""
        self.request_times.append(time.time())

# =========================================================
# CLIENT
# =========================================================

from google import genai

rate_limiter = RateLimiter(max_requests=15, time_window_seconds=120)

base_model = "gemma-4-31b-it"
api_key = "API_KEY"
client = genai.Client(api_key=api_key)

print("CWD: ", os.getcwd())

PROCESSED_LOG = "processed.txt"
FAILED_LOG = "failed.txt"

directorio = "./all_pages_clean/"
archivos = os.listdir(directorio)
try:
  archivos.remove('.ipynb_checkpoints')
except:
  pass
#print(archivos)


'''with open(file_path, "r", encoding="utf-8") as fh:
  input_text = fh.read()

print("\n\nTEXT:\n\n")
print(input_text[:1000])
print("\n\n\n\n")'''

archivos = sorted(os.listdir(DIRECTORIO))
if ".ipynb_checkpoints" in archivos:
    archivos.remove(".ipynb_checkpoints")

answers = load_progress(PROCESSED_LOG)
failed = load_failed_set(FAILED_LOG)

for file in archivos:
    file_id = file[:4]

    if file_id in failed:
        print(f"Saltando {file_id}: está en FAILED_LOG")
        continue

    if file_is_complete(file_id, answers):
        print(f"Saltando {file_id}: ya completo")
        continue

    print(f"\nProcesando {file}")
    print("Faltan:", get_missing_questions(file_id, answers))

    try:
        with open(os.path.join(DIRECTORIO, file), "r", encoding="utf-8") as fh:
            input_text = fh.read()

        for pregunta_func, q_name in zip(FORMULAIRE, QUESTIONS):
            done = len(answers[file_id].get(q_name, []))
            faltan = N_REPS - done

            if faltan <= 0:
                continue

            for _ in range(faltan):
                print(f"\t{q_name} ({done + 1}/{N_REPS})")

                message = pregunta_func(input_text)

                rate_limiter.wait_if_needed() # Esperar si es necesario antes de hacer la solicitud

                response = client.models.generate_content(
                    model=base_model,
                    contents=message,
                )

                rate_limiter.record_request() # Registrar la solicitud después de hacerla

                response_text = response.text if response.text is not None else ""

                append_log(PROCESSED_LOG, file_id, q_name, response_text)
                answers[file_id][q_name].append(response_text)

                done += 1

    except Exception as e:
        if file_id not in failed:
            failed.add(file_id)
            append_log(FAILED_LOG, file_id, "ERROR", repr(e))
        print("ERR:", file_id, repr(e))
        #cleanup_gpu()

# reconstruir CSV completo al final
rebuild_csv_from_log(PROCESSED_LOG, CSV_PATH)
print(f"\nCSV reconstruido en: {CSV_PATH}")